version: '3.1'

services:
  redis-non-ssl:
    image: redis:4-alpine3.11
    container_name: systemic-redis-defaults
    ports:
      - 6379:6379
    networks:
      - systemic-redis
  redis-ssl:
    image: redis:4-alpine3.11
    container_name: systemic-redis-custom
    command: redis-server --requirepass systemic-redis-custom-secret
    ports:
      - 6380:6379
    networks:
      - systemic-redis
networks:
  systemic-redis: {}
